openapi: 3.0.0

info:
  description: This is a simple API
  version: "1.0.0"
  title: Zombie API
servers:
  - url: https://zombie.151di5ffrvir.eu-gb.codeengine.appdomain.cloud
security:
  - basic_auth: []
paths:
  /zombie:
    post:
      summary: get zombie risk
      operationId: zombie
      description: zombie
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        '200':
          description: 200 response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZombieRisk'
components:
  schemas:
    ZombieRisk:
      type: object
      properties:
        location:
          type: string
        message:
          type: string
        risk:
          type: integer
    Location:
      type: object
      properties:
        location:
          type: string

  securitySchemes:
    basic_auth:
      type: http
      scheme: basic